export enum dashboardActionTypes {
    /* ==== ACTION TYPES===*/
    GET_SELECTED_CLUSTER = "GET_SELECTED_CLUSTER",
    GET_SELECTED_NAMESPACE = "GET_SELECTED_NAMESPACE",
    GET_SELECTED_DEPLOYMENT = "GET_SELECTED_DEPLOYMENT",
    GET_CLUSTER_LIST = "GET_CLUSTER_LIST",
    GET_CLUSTER_LIST_SUCCESS = "GET_CLUSTER_LIST_SUCCESS",
    GET_CLUSTER_DETAILS = "GET_CLUSTER_DETAILS",
    GET_CLUSTER_DETAILS_SUCCESS = "GET_CLUSTER_DETAILS_SUCCESS",
    GET_NAMESPACE_LIST = "GET_NAMESPACE_LIST",
    GET_NAMESPACE_LIST_SUCCESS = "GET_NAMESPACE_LIST_SUCCESS",
    GET_NAMESPACE_DETAILS = "GET_NAMESPACE_DETAILS",
    GET_NAMESPACE_DETAILS_SUCCESS = "GET_NAMESPACE_DETAILS_SUCCESS",
    GET_DEPLOYMENT_LIST = "GET_DEPLOYMENT_LIST",
    GET_DEPLOYMENT_LIST_SUCCESS = "GET_DEPLOYMENT_LIST_SUCCESS",
    GET_DEPLOYMENT_DETAILS = "GET_DEPLOYMENT_DETAILS",
    GET_DEPLOYMENT_DETAILS_SUCCESS = "GET_DEPLOYMENT_DETAILS_SUCCESS",
    ERROR = "ERROR",
    ERROR_RESET = "ERROR_RESET"
}