---
apiVersion: v1
kind: Pod
metadata:
 name: elotl-dashboard-deployment
 namespace: dashboard
 labels:
   app: elotl-dashboard-pod
spec:
  containers:
  - name: elotl-dashboard-container
    image: {{ ecr_image_base_uri }}:{{ image_tag }}
    ports:
    - containerPort: 4000
  restartPolicy: Never

---
apiVersion: v1
kind: Service
metadata:
 name: elotl-dashboard-service
 namespace: dashboard
spec:
 selector:
   app: elotl-dashboard-pod
 ports:
   - name: http
     protocol: TCP
     port: 80
     targetPort: 4000
 type: LoadBalancer
